controller_list:
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2
  - name: fake_both_arms_controller
    type: $(arg fake_execution_type)
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2
  - name: fake_left_hand_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_right_hand_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_head_controller
    type: $(arg fake_execution_type)
    joints:
      - head_pan
initial:  # Define initial robot poses per group
  - group: left_arm
    pose: left_neutral
  - group: right_arm
    pose: right_neutral
  - group: head
    pose: head_right